### ISSUE TITLE
Support rich text formatting on server

### ISSUE THREAD

**Issue by horaklukas** [AckeeCZ/gatsby-theme-localized#5]
To add support for rich [text formatting](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#enhanced-formattedmessage--formatmessage-rich-text-formatting) also at ssr mode we need to [polyfill DOM parser](https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#domparser). `gatsby-ssr.js` is a suitable place for it.

As mentioned at our meeting we need to handle import of `context` package, otherwise it would be failing.

**Comment by filip-dot-cube** [comment]
You mean this package? https://www.npmjs.com/package/react-intl-context

**Comment by horaklukas** [comment]
Sorry, I meant `canvas` not `context` 🙈
